Feature/7 mock offset and counts per rotation support
WisconsinRobotics/wroboclaw pull request #8
Opened 2022-11-15 01:02 UTC by JackZautner

Added support for setting counts per rotation and offsets for roboclaws. The real roboclaws will just read from the hardware but the mock ones will be able to read from a file, which will include the parameters. Important to note: Only the logic to do this has been implemented so far, I have not modified the parameter file.

2022-11-15 16:45 UTC, bennowotny requested changes
Some small fixes, noted in comments.

2022-11-15 16:45 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +    print(claw_defs_dto)
Don't think we want to keep this in a finalized version...

2022-11-15 16:45 UTC, bennowotny commented on src/wroboclaw/roboclaw/serial_interface.py
> +
Maybe comment to signal why these methods are do-nothings.

2022-11-15 16:45 UTC, bennowotny commented on src/wroboclaw/roboclaw/serial_interface.py
> +
Imagine someone else coming by in 2-3 years...
"These methods don't have any behavior; I'll just remove them!"
And the woe that befalls them afterwards.

2022-11-15 16:45 UTC, bennowotny commented on src/wroboclaw/util/mock.py
> +
If these methods are supposed to be publicly accessible (and they are, you use them that way, that's ok), they should not use the 'private' method convention of starting with an underscore.

2022-11-15 16:45 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +UINT32_MAX = (1 << 32) - 1
Should this go to the `util` package somewhere?  I don't know for certain, but now it's defined in two places (mock.py:8), even though it's the exact same constant.

2022-11-22 00:40 UTC, co-li approved these changes
Looks good to me, previous comments have been addressed.

2022-11-22 00:43 UTC, bennowotny requested changes

2022-11-22 00:43 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +from wroboclaw.roboclaw.mock import UINT32_BOUNDS
This should probably go to `util.py` based on where it's used.

2022-11-22 00:44 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +UINT32_MAX = (1 << 32) - 1
Complete as of cb491a0.

2022-11-22 00:44 UTC, bennowotny commented on src/wroboclaw/util/mock.py
> +
Complete as of cb491a0.

2022-11-22 00:44 UTC, bennowotny commented on src/wroboclaw/roboclaw/serial_interface.py
> +
Complete as of cb491a0.

2022-11-22 00:44 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +    print(claw_defs_dto)
Complete as of cb491a0.

2022-11-26 00:57 UTC, bennowotny approved these changes
Looks good.

2022-11-26 00:57 UTC, bennowotny commented on nodes/drive_roboclaw.py
> +from wroboclaw.roboclaw.mock import UINT32_BOUNDS
Resolved in aac6107.

2022-11-26 00:58 UTC, bennowotny commented
This still needs a sync merge before this can merge.  That can be done with the 'resolve conflicts' button, or, while in this branch:
`git pull origin master`
Which will cause a merge for all changes that have happened to the main branch while this was being developed.

2022-11-27 21:05 UTC, JackZautner commented
I resolved the merge conflict, not sure if there is anything we have to do before squash merging.

2022-11-27 22:09 UTC, bennowotny commented
@JackZautner If it's tested and it works, then it should be good to merge now.

When you're ready, click the merge button (should be green and say "squash and merge") to merge back to wroboclaw master.

2022-11-29 00:03 UTC, merged